### ISSUE TITLE
Electric Triangle - Physics - C++

### ISSUE THREAD

**Issue by caiodomingues** [BaReinhard/Hacktoberfest-Mathematics#159]
I've made a C++ version of the Electrical Triangle (Physics). Im fairly new to github and im having problems to do the Pull Request, so im doing a Issue report as a suggestion 😄

**Comment by caiodomingues** [comment]
[Snippet.cpp](https://github.com/BaReinhard/Hacktoberfest-Mathematics/files/1377479/Snippet.txt)

**Comment by BaReinhard** [comment]
In order to get credit for hacktoberfest, I would suggest taking a look at how to make pull request and adding files.

The easiest way for you right now would be to fork this repo, and create a new file on that repo. Then create the pull request.

Ill try to make a quick video for you if/when I have time.
